server:
  port: 8080
spring:
  application:
    name: "hac-erp"
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
app:
  jwt-secret: "KpmEgF/39ZnTZK63C5y7DOJKYN0f5Iwf0YwFYMQyyYY="
  jwt-expiration-milliseconds: 604800000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json

sonar:
  host:
    url: http://localhost:9000
  login: admin
  password: 12536478
  token: "sqp_da73249874332bd976a2f7b8719f7f96d96a2c74"
  projectKey: hac
  projectName: hac
#  h2:
#    console:
#      enabled: true
#      path: '/h2-console'
#  sql:
#    init:
#      mode: always
#      enabled: true
