server:
  port: 8080
spring:
  application:
    name: "hac-erp"
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
app:
  jwt-secret: "KpmEgF/39ZnTZK63C5y7DOJKYN0f5Iwf0YwFYMQyyYY="
  jwt-expiration-milliseconds: 604800000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
#  h2:
#    console:
#      enabled: true
#      path: '/h2-console'
#  sql:
#    init:
#      mode: always
#      enabled: true
