INSERT INTO users (id, username, password) VALUES
    (1, 'admin','$2a$10$wy6yy53B53sRgVJ/0q7u3OhJGX91obQDSYp1UqXqOv5c.3XxCQb7u');

INSERT INTO roles (id, name) VALUES (1,'ADMIN'),(2,'USER');

INSERT INTO users_roles VALUES (1,1);
INSERT INTO purchase_expenses_titles (name_ar, name_en)
VALUES
    ('مصاريف شحن','Shipping expenses'),
    ('مصاريف تخليص جمركي','Customs clearance expenses'),
    ('مصاريف اخرى','Other expenses');

INSERT INTO countries (name_ar, name_en)
VALUES
    ('أفغانستان', 'Afghanistan'),
    ('ألبانيا', 'Albania'),
    ('الجزائر', 'Algeria'),
    ('ساموا الأمريكية', 'American Samoa'),
    ('أندورا', 'Andorra'),
    ('أنغولا', 'Angola'),
    ('أنغيلا', 'Anguilla'),
    ('أنتيغوا وباربودا', 'Antigua and Barbuda'),
    ('الأرجنتين', 'Argentina'),
    ('أرمينيا', 'Armenia'),
    ('أروبا', 'Aruba'),
    ('أستراليا', 'Australia'),
    ('النمسا', 'Austria'),
    ('أذربيجان', 'Azerbaijan'),
    ('الباهاما', 'Bahamas'),
    ('البحرين', 'Bahrain'),
    ('بنغلاديش', 'Bangladesh'),
    ('بربادوس', 'Barbados'),
    ('بيلاروسيا', 'Belarus'),
    ('بلجيكا', 'Belgium'),
    ('بليز', 'Belize'),
    ('بنين', 'Benin'),
    ('برمودا', 'Bermuda'),
    ('بوتان', 'Bhutan'),
    ('بوليفيا', 'Bolivia'),
    ('البوسنة والهرسك', 'Bosnia and Herzegovina'),
    ('بوتسوانا', 'Botswana'),
    ('البرازيل', 'Brazil'),
    ('جزر فرسان البروناي', 'Brunei Darussalam'),
    ('بلغاريا', 'Bulgaria'),
    ('بوركينا فاسو', 'Burkina Faso'),
    ('بوروندي', 'Burundi'),
    ('كمبوديا', 'Cambodia'),
    ('الكاميرون', 'Cameroon'),
    ('كندا', 'Canada'),
    ('الرأس الأخضر', 'Cape Verde'),
    ('جمهورية أفريقيا الوسطى', 'Central African Republic'),
    ('تشاد', 'Chad'),
    ('تشيلي', 'Chile'),
    ('الصين', 'China'),
    ('كولومبيا', 'Colombia'),
    ('جزر القمر', 'Comoros'),
    ('الكونغو', 'Congo'),
    ('جزر كوك', 'Cook Islands'),
    ('كوستا ريكا', 'Costa Rica'),
    ('ساحل العاج', 'Cote d Ivoire'),
    ('كرواتيا', 'Croatia'),
    ('كوبا', 'Cuba'),
    ('قبرص', 'Cyprus'),
    ('التشيك', 'Czech Republic'),
    ('الدنمارك', 'Denmark'),
    ('جيبوتي', 'Djibouti'),
    ('دومينيكا', 'Dominica'),
    ('جمهورية الدومينيكان', 'Dominican Republic'),
    ('تيمور الشرقية', 'East Timor'),
    ('الإكوادور', 'Ecuador'),
    ('مصر', 'Egypt'),
    ('السلفادور', 'El Salvador'),
    ('غينيا الاستوائية', 'Equatorial Guinea'),
    ('إريتريا', 'Eritrea'),
    ('إستونيا', 'Estonia'),
    ('إثيوبيا', 'Ethiopia'),
    ('جزر فوكلاند', 'Falkland Islands'),
    ('جزر فارو', 'Faroe Islands'),
    ('فيجي', 'Fiji'),
    ('فنلندا', 'Finland'),
    ('فرنسا', 'France'),
    ('غويانا الفرنسية', 'French Guiana'),
    ('بولينيزيا الفرنسية', 'French Polynesia'),
    ('الجابون', 'Gabon'),
    ('غامبيا', 'Gambia'),
    ('جورجيا', 'Georgia'),
    ('ألمانيا', 'Germany'),
    ('غانا', 'Ghana'),
    ('جبل طارق', 'Gibraltar'),
    ('اليونان', 'Greece'),
    ('القرينادين', 'Grenada'),
    ('جوادلوب', 'Guadeloupe'),
    ('غوام', 'Guam'),
    ('غواتيمالا', 'Guatemala'),
    ('غينيا', 'Guinea'),
    ('غينيا بيساو', 'Guinea-Bissau'),
    ('غيانا', 'Guyana'),
    ('هايتي', 'Haiti'),
    ('هندوراس', 'Honduras'),
    ('هونغ كونغ', 'Hong Kong'),
    ('المجر', 'Hungary'),
    ('آيسلندا', 'Iceland'),
    ('الهند', 'India'),
    ('إندونيسيا', 'Indonesia'),
    ('إيران', 'Iran'),
    ('العراق', 'Iraq'),
    ('أيرلندا', 'Ireland'),
    ('إسرائيل', 'Israel'),
    ('إيطاليا', 'Italy'),
    ('جامايكا', 'Jamaica'),
    ('اليابان', 'Japan'),
    ('الأردن', 'Jordan'),
    ('كازاخستان', 'Kazakhstan'),
    ('كينيا', 'Kenya'),
    ('كيريباتي', 'Kiribati'),
    ('كوريا الشمالية', 'North Korea'),
    ('كوريا الجنوبية', 'South Korea'),
    ('الكويت', 'Kuwait'),
    ('قرغيزستان', 'Kyrgyzstan'),
    ('لاوس', 'Laos'),
    ('لاتفيا', 'Latvia'),
    ('لبنان', 'Lebanon'),
    ('ليسوتو', 'Lesotho'),
    ('ليبيريا', 'Liberia'),
    ('ليبيا', 'Libya'),
    ('ليختنشتاين', 'Liechtenstein'),
    ('ليتوانيا', 'Lithuania'),
    ('لوكسمبورغ', 'Luxembourg'),
    ('ماكاو', 'Macau'),
    ('مدغشقر', 'Madagascar'),
    ('مالاوي', 'Malawi'),
    ('ماليزيا', 'Malaysia'),
    ('جزر المالديف', 'Maldives'),
    ('مالي', 'Mali'),
    ('مالطا', 'Malta'),
    ('جزر مارشال', 'Marshall Islands'),
    ('مارتينيك', 'Martinique'),
    ('موريتانيا', 'Mauritania'),
    ('موريشيوس', 'Mauritius'),
    ('المكسيك', 'Mexico'),
    ('مايكرونيزيا', 'Micronesia'),
    ('مولدوفا', 'Moldova'),
    ('موناكو', 'Monaco'),
    ('منغوليا', 'Mongolia'),
    ('الجبل الأسود', 'Montenegro'),
    ('مونتسرات', 'Montserrat'),
    ('المغرب', 'Morocco'),
    ('موزمبيق', 'Mozambique'),
    ('ميانمار', 'Myanmar'),
    ('ناميبيا', 'Namibia'),
    ('ناورو', 'Nauru'),
    ('نيبال', 'Nepal'),
    ('هولندا', 'Netherlands'),
    ('كوراساو', 'Curacao'),
    ('نيوزيلندا', 'New Zealand'),
    ('نيكاراغوا', 'Nicaragua'),
    ('النيجر', 'Niger'),
    ('نيجيريا', 'Nigeria'),
    ('نيوي', 'Niue'),
    ('جزر نورفولك', 'Norfolk Island'),
    ('النرويج', 'Norway'),
    ('سلطنة عمان', 'Oman'),
    ('باكستان', 'Pakistan'),
    ('بالاو', 'Palau'),
    ('فلسطين', 'Palestine'),
    ('بنما', 'Panama'),
    ('بابوا غينيا الجديدة', 'Papua New Guinea'),
    ('باراغواي', 'Paraguay'),
    ('بيرو', 'Peru'),
    ('الفلبين', 'Philippines'),
    ('بيتكيرن', 'Pitcairn'),
    ('بولندا', 'Poland'),
    ('البرتغال', 'Portugal'),
    ('بورتوريكو', 'Puerto Rico'),
    ('قطر', 'Qatar'),
    ('رومانيا', 'Romania'),
    ('روسيا', 'Russia'),
    ('رواندا', 'Rwanda'),
    ('سانت بارتيلمي', 'Saint Barthelemy'),
    ('سانت هيلينا', 'Saint Helena'),
    ('سانت كيتس ونيفيس', 'Saint Kitts and Nevis'),
    ('سانت لوسيا', 'Saint Lucia'),
    ('سانت مارتن', 'Saint Martin'),
    ('سان بيير وميكولون', 'Saint Pierre and Miquelon'),
    ('ساموا', 'Samoa'),
    ('سان مارينو', 'San Marino'),
    ('ساو تومي وبرينسيب', 'Sao Tome and Principe'),
    ('المملكة العربية السعودية', 'Saudi Arabia'),
    ('السنغال', 'Senegal'),
    ('صربيا', 'Serbia'),
    ('سيشل', 'Seychelles'),
    ('سيراليون', 'Sierra Leone'),
    ('سنغافورة', 'Singapore'),
    ('سلوفاكيا', 'Slovakia'),
    ('سلوفينيا', 'Slovenia'),
    ('جزر سليمان', 'Solomon Islands'),
    ('الصومال', 'Somalia'),
    ('جنوب إفريقيا', 'South Africa'),
    ('جنوب السودان', 'South Sudan'),
    ('إسبانيا', 'Spain'),
    ('سريلانكا', 'Sri Lanka'),
    ('السودان', 'Sudan'),
    ('سورينام', 'Suriname'),
    ('سوازيلاند', 'Swaziland'),
    ('السويد', 'Sweden'),
    ('سويسرا', 'Switzerland'),
    ('سوريا', 'Syria'),
    ('تايوان', 'Taiwan'),
    ('طاجيكستان', 'Tajikistan'),
    ('تنزانيا', 'Tanzania'),
    ('تايلاند', 'Thailand'),
    ('توغو', 'Togo'),
    ('تونغا', 'Tonga'),
    ('ترينيداد وتوباغو', 'Trinidad and Tobago'),
    ('تونس', 'Tunisia'),
    ('تركيا', 'Turkey'),
    ('تركمانستان', 'Turkmenistan'),
    ('توفالو', 'Tuvalu'),
    ('أوغندا', 'Uganda'),
    ('أوكرانيا', 'Ukraine'),
    ('الإمارات العربية المتحدة', 'United Arab Emirates'),
    ('المملكة المتحدة', 'United Kingdom'),
    ('الولايات المتحدة', 'United States'),
    ('أوروغواي', 'Uruguay'),
    ('أوزبكستان', 'Uzbekistan'),
    ('فانواتو', 'Vanuatu'),
    ('فنزويلا', 'Venezuela'),
    ('فيتنام', 'Vietnam'),
    ('الجزر العذراء البريطانية', 'British Virgin Islands'),
    ('جزر فيرجن', 'US Virgin Islands'),
    ('واليس وفوتونا', 'Wallis and Futuna'),
    ('الصحراء الغربية', 'Western Sahara'),
    ('اليمن', 'Yemen'),
    ('زامبيا', 'Zambia'),
    ('زيمبابوي', 'Zimbabwe');


INSERT INTO machine_parts (name_ar, name_en, created_at, updated_at, is_active)
VALUES
    ('الكبائن', 'Cabs', NOW(), NOW(), TRUE),
    ('المحرك', 'Engine', NOW(), NOW(), TRUE),
    ('الملحقات', 'Attachments', NOW(), NOW(), TRUE),
    ('الفلاتر والسوائل', 'Filters & Fluids', NOW(), NOW(), TRUE),
    (' الهيدروليكية', 'Hydraulics', NOW(), NOW(), TRUE),
    ('الخراطيم والأنابيب', 'Hoses & Tubes', NOW(), NOW(), TRUE);


-- Inserting data into the stores table
INSERT INTO stores (name_ar, name_en, city_ar, city_en, created_at, updated_at, is_active)
VALUES
    ('مخازن جدة', 'Jeddah Stores', 'جدة', 'Jeddah', NOW(), NOW(), TRUE),
    ('مخازن مكة', 'Mecca Stores', 'مكة', 'Mecca', NOW(), NOW(), TRUE),
    ('مخازن الرياض', 'Riyadh Stores', 'الرياض', 'Riyadh', NOW(), NOW(), TRUE);

-- Inserting data into the store_locations table
INSERT INTO store_locations (name_ar, name_en, store_id, created_at, updated_at, is_active)
VALUES
    ('موقع 1', 'Location 1', 1, NOW(), NOW(), TRUE),
    ('موقع 2', 'Location 2', 1, NOW(), NOW(), TRUE),
    ('موقع 3', 'Location 3', 2, NOW(), NOW(), TRUE),
    ('موقع 4', 'Location 4', 3, NOW(), NOW(), TRUE);

-- Inserting data into the brands table
INSERT INTO brands (id, name_ar, name_en, code, main_brand_id, created_at, updated_at, is_active)
VALUES
    (1,'كاتربيلر', 'Caterpillar', 'CAT', NULL, NOW(), NOW(), TRUE),
    (2,'كوماتسو', 'komatsu', 'KOM', NULL, NOW(), NOW(), TRUE),
    (3,'دوسان', 'Doosan', 'Doos', NULL, NOW(), NOW(), TRUE),
    ('أصلي', 'Genuine', 'GG', 1, NOW(), NOW(), TRUE),
    ('أصلي', 'Genuine', 'GG', 2, NOW(), NOW(), TRUE),
    ('أصلي', 'Genuine', 'GG', 3, NOW(), NOW(), TRUE),
    ('اف بي ديزل', 'FP-Diesel', 'FP', 1, NOW(), NOW(), TRUE),
    ('Dsg', 'Dsg', 'Dsg', 1, NOW(), NOW(), TRUE),
    ('Dsm', 'Dsm', 'Dsm', 3, NOW(), NOW(), TRUE);


DELETE FROM brands
WHERE id > 0;
